### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Nickyshe** [mixpeek/docs#4]
Path: /introduction/libraries
Is it just one library mix peek supports?
![2024-06-17 03_47_12-Libraries - Mixpeek](https://github.com/mixpeek/docs/assets/110067624/a11bd2f5-cdcf-4312-ac97-6b810058f804)

The List of supported libraries should come first before adding the link to contact engineers for preferred libraries. This page should not be on the getting started group

@esteininger

**Comment by esteininger** [comment]
https://github.com/mixpeek/docs/commit/99723fcf9606dad9a75cb712ad38de496ae5256d
